### PR TITLE
Update Elyra to v2.2.4

### PR DESCRIPTION
**Pull request by akchinSTC**
## Related Issues and Dependencies

…

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Bumps Elyra to version 2.2.4

## Description

Bumps Elyra to version 2.2.4
Change log:
https://github.com/elyra-ai/elyra/blob/master/docs/source/getting_started/changelog.md

### CODE REVIEW

**Comment by akchinSTC** [comment]
weird, did the CI get disabled for this repo?

**Comment by harshad16** [comment]
having an issue in the cluster, working on it to fix this.

**Review by harshad16 — APPROVED** [review]
lgtm
thanks for the update

**Pull request merged**
