### PR TITLE
Update Elyra to v1.3.3

### PR DESCRIPTION
**Pull request by akchinSTC**
## Related Issues and Dependencies

This update resolves the write permissions issue when attempting
to run !pip install within notebook cells.

Conversation here: https://github.com/opendatahub-io/odh-manifests/pull/203

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Updates to latest version with the fix

## Description

Elyra will now map the emptydir volume when running in kfp to the same root dir as the elyra img for write consistency (/opt/app-root/src) 
Python paths and target directories have been changed to write to the same volume.

### CODE REVIEW

**Comment by akchinSTC** [comment]
@vpavlin - can this be merged?

**Comment by vpavlin** [comment]
This looks good to me, I wanted to test it, but the build failed to push. Checking with @harshad16 to make sure any CI issue is resolved before we merge & release. I'll get back to this a bit later today.

**Comment by vpavlin** [comment]
The push succeeded and I was able to start Elyra notebook (did not attempt to run a pipeline). LGTM

**Comment by vpavlin** [comment]
@akchinSTC FYI there is a new image available at quay.io/thoth-station/s2i-lab-elyra:v0.0.5

**Comment by akchinSTC** [comment]
@vpavlin  - thank you! testing now and updating the existing open PR in odh-manifets

**Pull request merged**
