### PR TITLE
Update Elyra to v2.0

### PR DESCRIPTION
**Pull request by akchinSTC**
- Adds support for Tekton compiler/engine in KFP

## Related Issues and Dependencies

…

## This introduces a breaking change

- [ ] Yes
- [X] No

## This Pull Request implements

This PR updates the Elyra image to v2.0.1 that includes support for Tekton when used with KFP, which is the default compiler in ODH

## Description

Add support for Kubeflow Pipelines using Argo and Tekton engines

Add support for JupyterLab 3.x
Add new Language Server Protocol (LSP) capabilities
Publishing Elyra images to both docker.io and quay.io
Multiple updates to overall documentation
Increased test coverage

Changelog here:
https://elyra.readthedocs.io/en/latest/getting_started/changelog.html

### CODE REVIEW

**Comment by akchinSTC** [comment]
@vpavlin - is anyone able to grant me read access to the CI logs so I can diagnose the failing issue?

**Comment by akchinSTC** [comment]
@nakfour - Hi Juana, is there anyone available to review this issue? I would welcome access to the CI logs as well and to diagnose the issue myself. I also do not have rights to assign this issue (not even to myself)

**Comment by vpavlin** [comment]
@akchinSTC Sorry for the delay...can you also change the base image here: https://github.com/opendatahub-io/s2i-lab-elyra/blob/master/.aicoe-ci.yaml#L4?

**Comment by akchinSTC** [comment]
@vpavlin - Hi Vaclav! Did you need me to change it back to the previous minimal image? This PR updated that line to use `quay.io/thoth-station/s2i-minimal-py38-notebook`

**Comment by vpavlin** [comment]
@akchinSTC Ah, I see where the issue is - you changed the Pipfile, but did not run `pipenv lock`, so lock still requires Python 3.6

**Comment by vpavlin** [comment]
Cool, the build now proceeds, but we get another error:

```
+ jupyter lab build
[LabBuildApp] JupyterLab 3.0.7
[LabBuildApp] Building in /opt/app-root/share/jupyter/lab
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don'\''t already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (i.e., the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab'\''s overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occured.
ValueError: Please install nodejs >=12.0.0 before continuing. nodejs may be installed using conda or directly from the nodejs website.
See the log file for details:  /tmp/jupyterlab-debug-_2mwq5j2.log
subprocess exited with status 1
subprocess exited with status 1
error building at STEP "RUN /tmp/scripts/assemble": exit status 1'
```

CC @harshad16

**Comment by harshad16** [comment]
I will have look at the nodejs issue. 
btw, @akchinSTC do we want the update of https://github.com/opendatahub-io/s2i-lab-elyra/pull/14 to go in.

**Comment by akchinSTC** [comment]
@harshad16 - ill be closing #14 since Elyra 1.5.3 does not support kfp-tekton while is now the default compiler in use with kubeflow pipelines in ODH.

@vpavlin - thanks for the tip! Ill update readme with build steps as well, maybe it can help others with new notebook image contributions for ODH.

**Comment by harshad16** [comment]
As stated in the log of https://github.com/opendatahub-io/s2i-lab-elyra/pull/16#issuecomment-776671591
the jupyterlab 3 which is the requirement of elyra 2, requires nodesjs > 12.0 
we are working on installing it in the base image, so the transition happens well ordered.

**Comment by harshad16** [comment]
This issue is being fixed in the s2i-minimal-notebook.
The requirements of nodejs are updated in the s2i-minimal, it is being tested.
Should be in a couple of days. 
For now, we have created an image out of this PR: `quay.io/thoth-station/s2i-lab-elyra:jupyterlab-elyra2.x`

**Comment by pacospace** [comment]
> This issue is being fixed in the s2i-minimal-notebook.
> The requirements of nodejs are updated in the s2i-minimal, it is being tested.
> Should be in a couple of days.
> For now, we have created an image out of this PR: `quay.io/thoth-station/s2i-lab-elyra:jupyterlab-elyra2.x`

Running that image locally seems to have no issues. I tested the same image spawned from JH on ODH on Operate First and It gives error:

Screenshot from 2021-02-17 14-20-11

Screenshot from 2021-02-17 14-20-39

and also Git extension issues:

Screenshot from 2021-02-17 16-11-36

cc @akchinSTC @harshad16 @vpavlin

**Comment by pacospace** [comment]
> > This issue is being fixed in the s2i-minimal-notebook.
> > The requirements of nodejs are updated in the s2i-minimal, it is being tested.
> > Should be in a couple of days.
> > For now, we have created an image out of this PR: `quay.io/thoth-station/s2i-lab-elyra:jupyterlab-elyra2.x`
> 
> Running that image locally seems to have no issues. I tested the same image spawned from JH from ODH on Operate First and It gives error:
> 
> Screenshot from 2021-02-17 14-20-11
> 
> Screenshot from 2021-02-17 14-20-39
> 
> and also Git extension issues:
> 
> Screenshot from 2021-02-17 16-11-36
> 
> cc @akchinSTC @harshad16 @vpavlin

Looking at pod logs from JH:

```
[W 2021-02-19 08:47:16.249 SingleUserLabApp notebookapp:1995] Error loading server extension @elyra/metadata-extension
    Traceback (most recent call last):
      File "/opt/app-root/lib64/python3.8/site-packages/notebook/notebookapp.py", line 1988, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
    ModuleNotFoundError: No module named '@elyra/metadata-extension'
```

**Comment by pacospace** [comment]
In Jupyterlab3 

```
Jupyter Server
JupyterLab 3.0 now depends on Jupyter Server, which is a new Jupyter project based on the server portion of the classic Notebook server. See the Migration Guide to migrate custom notebook configuration to Jupyter Server.
```
Source: https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#v3-0-0

```
Migrating from Notebook Server
To migrate from notebook server to plain jupyter server, follow these steps:

Rename your jupyter_notebook_config.py file to jupyter_server_config.py.

Rename all c.NotebookApp traits to c.ServerApp.

For example if you have the following jupyter_notebook_config.py.

c.NotebookApp.allow_credentials = False
c.NotebookApp.port = 8889
c.NotebookApp.password_required = True
You will have to create the following jupyter_server_config.py file.

c.ServerApp.allow_credentials = False
c.ServerApp.port = 8889
c.ServerApp.password_required = True
```

Source: https://jupyter-server.readthedocs.io/en/stable/operators/migrate-from-nbserver.html

Updates required in: https://github.com/thoth-station/s2i-minimal-notebook/blob/master/start-notebook.sh#L46

**Comment by pacospace** [comment]
> In Jupyterlab3
> 
> ```
> Jupyter Server
> JupyterLab 3.0 now depends on Jupyter Server, which is a new Jupyter project based on the server portion of the classic Notebook server. See the Migration Guide to migrate custom notebook configuration to Jupyter Server.
> ```
> 
> Source: https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#v3-0-0
> 
> ```
> Migrating from Notebook Server
> To migrate from notebook server to plain jupyter server, follow these steps:
> 
> Rename your jupyter_notebook_config.py file to jupyter_server_config.py.
> 
> Rename all c.NotebookApp traits to c.ServerApp.
> 
> For example if you have the following jupyter_notebook_config.py.
> 
> c.NotebookApp.allow_credentials = False
> c.NotebookApp.port = 8889
> c.NotebookApp.password_required = True
> You will have to create the following jupyter_server_config.py file.
> 
> c.ServerApp.allow_credentials = False
> c.ServerApp.port = 8889
> c.ServerApp.password_required = True
> ```
> 
> Source: https://jupyter-server.readthedocs.io/en/stable/operators/migrate-from-nbserver.html
> 
> Updates required in: https://github.com/thoth-station/s2i-minimal-notebook/blob/master/start-notebook.sh#L46
Maybe this file needs to have two versions? based on the image base if has jupyterlab2 or 3?

Not sure what is the requirement for backward compatibility of this base image, but this might be taken into account:

```
Running Jupyter Notebook on Jupyter Server
If you want to switch to Jupyter Server, but you still want to serve Jupyter Notebook to users, you can try NBClassic.

NBClassic is a Jupyter Server extension that serves the Notebook frontend (i.e. all static assets) on top of Jupyter Server. It even loads Jupyter Notebook’s config files.

Warning

NBClassic will only work for a limited time. Jupyter Server is likely to evolve beyond a point where Jupyter Notebook frontend will no longer work with the underlying server. Consider switching to JupyterLab or nteract where there is active development happening.
```
Source: https://jupyter-server.readthedocs.io/en/stable/operators/migrate-from-nbserver.html#running-jupyter-notebook-on-jupyter-server

**Comment by pacospace** [comment]
Can be an incompatible version of JH with Jupyterlab > 3.0.0? Tha would explain why image running from local pod works correctly and from JH not.

```
1.2.0 2020-10-29¶
JupyterHub 1.2 is an incremental release with lots of small improvements. It is unlikely that users will have to change much to upgrade, but lots of new things are possible and/or better!

There are no database schema changes requiring migration from 1.1 to 1.2.

Highlights:

Deprecate black/whitelist configuration fields in favor of more inclusive blocked/allowed language. For example: c.Authenticator.allowed_users = {'user', ...}

More configuration of page templates and service display

Pagination of the admin page improving performance with large numbers of users

Improved control of user redirect

-> **Support for jupyter-server-based single-user servers, such as Voilà and latest JupyterLab.**

Lots more improvements to documentation, HTML pages, and customizations
```

**Comment by vpavlin** [comment]
JH in ODH 1.0 is 1.2.1 - https://github.com/opendatahub-io/jupyterhub-quickstart/blob/master/requirements.txt

JH in the s2i-minimal is 1.1.0 - https://github.com/thoth-station/s2i-minimal-notebook/blob/master/Pipfile#L10

I'll send a patch..

**Comment by harshad16** [comment]
The Update of JH to 1.2.1 from 1.1.0 and the change of Notebook.app to Server.app together has resolved the issue of the elyra not being able to find endpoints.

**Comment by vpavlin** [comment]
@harshad16 mentioned there is one more things missing which will be added in a follow up PR..merging

**Pull request merged**
