### PR TITLE
Update elyra version to 3.9.1

### PR DESCRIPTION
**Pull request by akchinSTC**
## Related Issues and Dependencies
No related issues. This bumps Elyra to 3.9.1. 

New features can be found in the following links: (See all links for all features, last published version of elyra was 3.6.0 in ODH)
https://github.com/elyra-ai/elyra/releases/tag/v3.9.1
https://github.com/elyra-ai/elyra/releases/tag/v3.9.0
https://github.com/elyra-ai/elyra/releases/tag/v3.8.0
https://github.com/elyra-ai/elyra/releases/tag/v3.7.0

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Updates the elyra package to v3.9.1.
Full list of changes available here : https://elyra.readthedocs.io/en/latest/getting_started/changelog.html#release-3-9-1-06-10-2022

### CODE REVIEW

**Comment by akchinSTC** [comment]
Is there a way for me to access the log with the CI/build failures ?

**Comment by harshad16** [comment]
Hello @akchinSTC , the logs should be public.
However they are only presisted for 3hr.
i will re-trigger and check what is happening.

**Comment by harshad16** [comment]
this is failing on the jupyterlab build section, the logs of jupyterlab build are not available on build level,
so we would have to build this manually and test it.

**Comment by harshad16** [comment]
This seems to be building properly in local , going to approve this

**Comment by harshad16** [comment]
> not sure if im reading the log output correctly, is my aicoe.yaml CI configuration incorrect?
hmm, can you reach here: https://tekton.operate-first.cloud/#/namespaces/opf-ci-pipelines/pipelineruns/aicoe-pipelinerun-c8c4fb97-191d-476e-8dda-31cba73d5b64?pipelineTask=pr-build-run&step=run-build

the build info can be found at:
`> pr-build-run > run-build`

**Comment by harshad16** [comment]
The release is done, image can be found here: https://quay.io/repository/thoth-station/s2i-lab-elyra?tab=tags

**Pull request merged**
