### PR TITLE
Update Elyra to v3.6.0

### PR DESCRIPTION
**Pull request by akchinSTC**
## Related Issues and Dependencies

…

## This introduces a breaking change

- [x] Yes
- [ ] No

Auto-migration of older pipeline files to the new schema will be handled by the built in pipeline editor
## This Pull Request implements
This PR updates Elyra to v3.6.0

## Description

This PR updates the elyra python pkg to v3.6.0.

### CODE REVIEW

**Comment by akchinSTC** [comment]
@vpavlin  - Its been a while since elyra was updated and was looking for a base image/template to rebuild this image. Not entirely sure if these changes meet the new build process requirements.

**Comment by akchinSTC** [comment]
NP!, is this image template still the correct way to create an image for ODH or is there another one I should be using?

**Comment by harshad16** [comment]
As of now, this is still valid,
the new template ( if any) might come after the Q2.

**Comment by harshad16** [comment]
the test looks to be good :100:

**Comment by akchinSTC** [comment]
@harshad16 - thanks for updates. Is this still the correct location where the container images will be published ?
https://quay.io/repository/thoth-station/s2i-lab-elyra?tab=tags

**Comment by akchinSTC** [comment]
@harshad16 - any issues with the deployment? wondering if there is anything else I need to do?

**Comment by harshad16** [comment]
> Is this still the correct location where the container images will be published ?
yes it would published on https://quay.io/repository/thoth-station/s2i-lab-elyra?tab=tags

>  any issues with the deployment? wondering if there is anything else I need to do?
the build pipeline had an issue was fixing it, it should be good now.
:+1: 
will just build and test once , and then merge
thanks for the patience

**Comment by harshad16** [comment]
lgtm
thanks for the pr :100:

**Comment by akchinSTC** [comment]
@harshad16 - you the man and thanks!

**Pull request merged**
