### PR TITLE
Test jupyterlab-requirements v0.6.3

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies

Testing jupyterlab-requirements v0.6.3 with Elyra 2.* in the cluster

### CODE REVIEW

**Comment by pacospace** [comment]
@harshad16 what is the status here?

**Comment by pacospace** [comment]
Related-To: https://github.com/operate-first/support/issues/140

**Comment by harshad16** [comment]
operate-first team is taking decision on how they would be setting up the stagging namespace. 
For now probably we can add the pr image in the operate-first jupyterhub.

**Comment by pacospace** [comment]
> operate-first team is taking decision on how they would be setting up the stagging namespace.
> For now probably we can add the pr image in the operate-first jupyterhub.

What about updating the ml-workflow-prague image only?

**Comment by harshad16** [comment]
> What about updating the ml-workflow-prague image only?

sounds good to me,
i will make the change

**Comment by pacospace** [comment]
> > What about updating the ml-workflow-prague image only?
> 
> sounds good to me,
> i will make the change

Thanks @harshad16 !!

**Comment by pacospace** [comment]
> It is updated please test it.

`pipenv, version 2020.11.15` cannot solve dependencies for elyra 2.0.1:

```
pipenv.exceptions.ResolutionFailure: ERROR: Could not find a version that matches pycodestyle<2.7.0,>=2.6.0,>=2.7.0 (from autopep8==1.5.6->elyra==2.0.1->-r /tmp/pipenvkxllm99wrequirements/pipenv-h_tjs9zt-constraints.txt (line 2))
Tried: 2.0.0, 2.0.0, 2.1.0, 2.1.0, 2.2.0, 2.2.0, 2.3.0, 2.3.0, 2.3.1, 2.3.1, 2.4.0, 2.4.0, 2.5.0, 2.5.0, 2.6.0, 2.6.0, 2.7.0, 2.7.0
Skipped pre-versions: 1.8.0.dev0, 1.8.0.dev0, 2.0.0a1, 2.0.0a1, 2.6.0a1, 2.6.0a1
There are incompatible versions in the resolved dependencies:
  pycodestyle<2.7.0,>=2.6.0 (from python-language-server[all]==0.36.2->elyra==2.0.1->-r /tmp/pipenvkxllm99wrequirements/pipenv-h_tjs9zt-constraints.txt (line 2))
  pycodestyle>=2.7.0 (from autopep8==1.5.6->elyra==2.0.1->-r /tmp/pipenvkxllm99wrequirements/pipenv-h_tjs9zt-constraints.txt (line 2))
 ```

**Pull request closed without merging**
